 server:
   port: 8765

 spring:
   application:
      name: API-GATEWAY
       
   cloud:
     gateway: 
        routes:
           - id: team-route
             uri: lb://TEAM-SERVICE
             predicates:
               - Path=/team/api/**  
           - id: player-route
             uri: lb://PLAYER-SERVICE
             predicates:
               - Path=/player/api/**  
               
   eureka:
     client:
       service:
         url-default-zone:  http://localhost:8761/eureka/            
           
